### ISSUE TITLE
Error on GitHub runners: Parameter 'Encoding' not found in Get-Content

### ISSUE THREAD

**Issue by frottke** [SimonOfHH/D365BCAppHelper#21]
Hi @SimonOfHH,

First of all, thank you very much for creating this module. I use it really often and it has become an essential tool for me. That's also the reason why I want to integrate it into a pull request check.

I currently call the command for checking the licence for unlicensed objects via powershell 7. However, I get the following error on github runners (windows-latest and ubuntu-latest) and I can't find the issue. 
Perhaps you can help me.

```
Get-InfoFromBcLicenseFile: C:\Users\runneradmin\Documents\PowerShell\Modules\D365BCAppHelper\0.0.0.29\Export\Public\Get-D365BCLicenseInfo.ps1:186
Line |
 186 |          Get-InfoFromBcLicenseFile -LicensInfoFile $LicensInfoFile -Li …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | A parameter cannot be found that matches parameter name 'Encoding'.
```

I was able to track it down to this line of code https://github.com/SimonOfHH/D365BCAppHelper/blob/5f861add893643c7ea3aa9afd3a34f0af83184da/Export/Public/Get-D365BCLicenseInfo.ps1#L148

I tested if the problem also exists if I use some hardcoded value directly via powershell in my yaml file. It works there, it really looks like there is a problem this line of code.

**Comment by frottke** [comment]
I was able to find the issue. A typo in a path for testing purposes rendered an path invalid. therefore the file was not found which resulted in the error. Perhaps you could add a check if under the provided file path exists a file? :)

**Comment by SimonOfHH** [comment]
Hi @frottke 
thanks for reporting and - therefore - contributing to this little module :) I'll took a note and will incorporate a check the next time I'm working on this repo.
Thanks again and cheers, Simon
