### ISSUE TITLE
Add an example for the dependencies included in the manifest xml

### ISSUE THREAD

**Issue by pri-kise** [SimonOfHH/D365BCAppHelper#5]
I was looking for the dependencies of an app and thought at first that I don't get these values with the manifest xml.

Then I checked the result and was happy to see that the dependencies are part of the xml, too.
Maybe you could add an example to retrieve those values from the xml or at least mention the dependencies node in the file https://github.com/SimonOfHH/D365BCAppHelper/blob/master/Export/Private/Get-D365BCManifestFromAppFile.ps1

**Comment by SimonOfHH** [comment]
Hi @pri-kise I'm really sorry, that I didn't see this issue you raised. For some reason I didn't get a notification from GitHub for this issue (at least I think so). 
As with your other raised issue: I'll look into this over the weekend. If you have a nice proposal feel free to create a PR in advance 👍

**Comment by SimonOfHH** [comment]
HI @pri-kise with commit cafa541 I added a new function `D365BCDependenciesFromFile`. See description in updated [README](https://github.com/SimonOfHH/D365BCAppHelper#get-d365BCDependenciesFromFile).

If you encounter anything else feel free to open another issue :)
