### ISSUE TITLE
Problem with two concurring processes that export the manifest of the same app

### ISSUE THREAD

**Issue by pri-kise** [SimonOfHH/D365BCAppHelper#6]
I have a problem that the function `Get-D365BCManifestFromAppFile` only uses the filename and no guid.
This can sometimes result in a problem when I have multiple background jobs exporting the manifest for the exact same app.

Maybe one could add a new guid to the `$targetTempFolder`?
https://github.com/SimonOfHH/D365BCAppHelper/blob/c4293fd4903441c7d61dbe3c9d87560d735e9f8c/Export/Private/Get-D365BCManifestFromAppFile.ps1#L79
@SimonOfHH  What do think about that?

**Comment by SimonOfHH** [comment]
Hi @pri-kise thanks for your input. I'll look into this over the weekend. If you already have a modified and tested version available, feel free to create a Pull Request 😊

**Comment by SimonOfHH** [comment]
Hi @pri-kise with commit d30d2c6 I added a GUID to the temporary path. Hope this solves your problem :)

If you encounter anything else, feel free to open another issue :)
