### ISSUE TITLE
Problems with "Umlaute" - Missing Encoding

### ISSUE THREAD

**Issue by pri-kise** [SimonOfHH/D365BCAppHelper#7]
I'm using your powershell Module with some App Files of Publishers with a "Umlaut" and it seems that those aren't read correct from the file.
Maybe the Encoding has to be added to the procedure Get-Content.
`Get-Content -Path $ManifestFileName -Encoding Utf8`

Maybe a better alternative would be to load the Content directly into a XmlDocument to let the XML Parser handle the Encoding.
I'm not sure what might be the better solution.

https://github.com/SimonOfHH/D365BCAppHelper/blob/c478756cfc5551966cb1a56cc009054c25aaf141/Export/Private/Get-D365BCManifestFromAppFile.ps1#L232

**Comment by SimonOfHH** [comment]
Hi @pri-kise 
Thanks for reporting this 👍 I'll try to look into this over the weekend. Is there anything specific to reproduce this or can I create any app to test this that has an Umlaut in it? Is it just showing some weird character in the end or how does the problem show?

**Comment by duichwer** [comment]
@SimonOfHH I had problems with Umlauts in the publisher.
And it was a app without source code, only with binaries, though maybe this might be important,too?
(Note: my private Account)

**Comment by SimonOfHH** [comment]
Hmm, alright. I'll try to reproduce the problem and will keep you posted 👍

**Comment by SimonOfHH** [comment]
Hi @pri-kise @duichwer I was able to reproduce the issue. The manifest is now read with Utf8-encoding and values with special characters/umlauts are now returned correctly 👍
